import { createFileRoute } from "@tanstack/react-router";
import { AppHeader } from "@/components/dashboard/AppHeader";

export const Route = createFileRoute("/help")({
  component: HelpPage,
});

function HelpPage() {
  return (
    <div className="min-h-screen">
      <AppHeader title="Help" showHelp={false} backTo="/dashboard" />

      <main className="mx-auto max-w-md px-4 py-6">
        <div className="space-y-5">
          <section className="rounded-2xl border border-border/60 bg-card p-4 shadow-sm">
            <h2 className="text-xl font-bold text-foreground">
              How Your Dashboard Metrics Are Calculated
            </h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              This page explains what each dashboard metric means, how it is
              calculated, and how to interpret your score, rank, and status.
            </p>
          </section>

          <HelpSection title="Critical Performance">
            <MetricHelp
              title="D0 TTPU"
              period="Latest 200 users"
              unit="Minutes"
              description="Average talktime per new user on their first day of interaction with you."
              formula="D0 TTPU = Total D0 Talktime ÷ Distinct New Users"
              notes={[
                "Only completed bookings are included.",
                "Only your latest 200 distinct users are considered.",
                "If there are fewer than 200 eligible users, the dashboard may show insufficient data.",
              ]}
            />

            <MetricHelp
              title="D14 TTPU"
              period="Latest 200 mature users"
              unit="Minutes"
              description="Average cumulative talktime generated by a user within 14 days of their first interaction with you."
              formula="D14 TTPU = Total 14-Day Talktime ÷ Distinct Mature Users"
              notes={[
                "Only users whose first interaction happened at least 14 days ago are included.",
                "Only completed bookings within the first 14 days are counted.",
              ]}
            />
          </HelpSection>

          <HelpSection title="Profile Performance">
            <MetricHelp
              title="Average Chat Rating"
              period="Last 90 days"
              unit="Rating"
              description="Average rating received from repeat chat consultations."
              formula="Average Rating = Total Ratings ÷ Rated Bookings"
              notes={[
                "Only submitted ratings above 0 are included.",
                "Only repeat bookings are counted.",
                "Requires at least 13 rated chat bookings.",
              ]}
            />

            <MetricHelp
              title="Average Audio Rating"
              period="Last 90 days"
              unit="Rating"
              description="Average rating received from repeat audio consultations."
              formula="Average Rating = Total Ratings ÷ Rated Bookings"
              notes={[
                "Only submitted ratings above 0 are included.",
                "Only repeat bookings are counted.",
                "Requires at least 7 rated audio bookings.",
              ]}
            />

            <MetricHelp
              title="Average Video Rating"
              period="Last 90 days"
              unit="Rating"
              description="Average rating received from repeat video consultations."
              formula="Average Rating = Total Ratings ÷ Rated Bookings"
              notes={[
                "Only submitted ratings above 0 are included.",
                "Only repeat bookings are counted.",
                "Requires at least 3 rated video bookings.",
              ]}
            />
          </HelpSection>

          <HelpSection title="Availability Performance">
            <MetricHelp
              title="Chat Available Hours"
              period="Last 7 days"
              unit="Hours per day"
              description="Average daily time you were available for chat."
              formula="Available Hours = Total Available Time ÷ 7"
              notes={[
                "Availability intervals are merged to avoid double-counting overlapping time.",
              ]}
            />

            <MetricHelp
              title="Audio Available Hours"
              period="Last 7 days"
              unit="Hours per day"
              description="Average daily time you were available for audio calls."
              formula="Available Hours = Total Available Time ÷ 7"
              notes={[
                "Availability intervals are merged to avoid double-counting overlapping time.",
              ]}
            />

            <MetricHelp
              title="Video Available Hours"
              period="Last 7 days"
              unit="Hours per day"
              description="Average daily time you were available for video calls."
              formula="Available Hours = Total Available Time ÷ 7"
              notes={[
                "Availability intervals are merged to avoid double-counting overlapping time.",
              ]}
            />
          </HelpSection>

          <HelpSection title="Earnings Overview">
            <MetricHelp
              title="Last 7 Days Earnings"
              period="Last 7 days"
              unit="INR"
              description="Total expert earnings credited in the last 7 days."
              formula="Earnings = Sum of completed expert earning transactions"
              notes={["Only completed expert earning transactions are included."]}
            />

            <MetricHelp
              title="Last 14 Days Earnings"
              period="Last 14 days"
              unit="INR"
              description="Total expert earnings credited in the last 14 days."
              formula="Earnings = Sum of completed expert earning transactions"
              notes={["Only completed expert earning transactions are included."]}
            />

            <MetricHelp
              title="Last 30 Days Earnings"
              period="Last 30 days"
              unit="INR"
              description="Total expert earnings credited in the last 30 days."
              formula="Earnings = Sum of completed expert earning transactions"
              notes={["Only completed expert earning transactions are included."]}
            />
          </HelpSection>

          <HelpSection title="Weekly Funnel Trends">
            <InfoBlock
              title="What this section shows"
              text="Weekly Funnel Trends shows how new and repeat users moved through your funnel over the last 7 completed days. Today is excluded because today’s data may still be incomplete."
            />

            <InfoBlock
              title="D0 vs Dn"
              text="D0 means users interacting with you on their first interaction day. Dn means repeat users who came back after their first interaction day."
            />

            <MetricHelp
              title="D0 Users"
              period="Last 7 completed days"
              unit="Users"
              description="Unique new users who interacted with you on each day."
              formula="D0 Users = Distinct new users on that day"
              notes={["Only completed consultations are included."]}
            />

            <MetricHelp
              title="D0 ATT"
              period="Last 7 completed days"
              unit="Minutes"
              description="Average talktime per new user on their first interaction day."
              formula="D0 ATT = Total D0 Talktime ÷ Distinct D0 Users"
              notes={[
                "ATT means Average Talktime per User.",
                "If there are no users on a day, ATT is shown as 0.",
              ]}
            />

            <MetricHelp
              title="D0 Earnings"
              period="Last 7 completed days"
              unit="INR"
              description="Earnings generated from new users on each day."
              formula="D0 Earnings = Sum of expert earnings from D0 bookings"
              notes={["Only completed expert earning transactions are included."]}
            />

            <MetricHelp
              title="Dn Users"
              period="Last 7 completed days"
              unit="Users"
              description="Unique repeat users who interacted with you on each day."
              formula="Dn Users = Distinct repeat users on that day"
              notes={["Only completed consultations are included."]}
            />

            <MetricHelp
              title="Dn ATT"
              period="Last 7 completed days"
              unit="Minutes"
              description="Average talktime per repeat user on each day."
              formula="Dn ATT = Total repeat-user talktime ÷ Distinct repeat users"
              notes={[
                "ATT means Average Talktime per User.",
                "If there are no repeat users on a day, ATT is shown as 0.",
              ]}
            />

            <MetricHelp
              title="Dn Earnings"
              period="Last 7 completed days"
              unit="INR"
              description="Earnings generated from repeat users on each day."
              formula="Dn Earnings = Sum of expert earnings from repeat-user bookings"
              notes={["Only completed expert earning transactions are included."]}
            />

            <InfoBlock
              title="Trend %"
              text="Trend percentage compares the latest day with the first day in the 7-day window. Formula: (Latest Day Value - First Day Value) ÷ First Day Value × 100."
            />

            <InfoBlock
              title="Weekly Average and Best Day"
              text="Weekly Average is the average of the 7 daily values. Best Day is the weekday with the highest value for that metric."
            />
          </HelpSection>

          <HelpSection title="Utilisation Overview">
            <MetricHelp
              title="Busy Time"
              period="Last 7 days"
              unit="Hours"
              description="Total consultation time spent in completed bookings."
              formula="Busy Time = Total completed consultation time"
              notes={[
                "Shown separately for chat, audio, and video.",
                "Overlapping booking intervals are merged to avoid double-counting.",
              ]}
            />

            <MetricHelp
              title="Online Time"
              period="Last 7 days"
              unit="Hours"
              description="Total time you were online or available for a service."
              formula="Online Time = Total online availability time"
              notes={[
                "Shown separately for chat, audio, and video.",
                "Overlapping availability intervals are merged to avoid double-counting.",
              ]}
            />

            <MetricHelp
              title="Utilisation"
              period="Last 7 days"
              unit="Percent"
              description="Percentage of online time that was converted into consultation time."
              formula="Utilisation = Busy Hours ÷ Effective Online Hours × 100"
              notes={[
                "Effective online time uses online availability plus busy intervals, merged together.",
                "Shown separately for chat, audio, and video.",
              ]}
            />
          </HelpSection>

          <HelpSection title="Rank, Status and Benchmarks">
            <InfoBlock
              title="Rank"
              text="Your rank compares you with other active experts in your primary language group for the same metric."
            />

            <InfoBlock
              title="Status"
              text="Weak, Average, Strong, and Elite are based on percentile performance. Elite means above the 95th percentile, Strong means above the 90th percentile, Average means above the 75th percentile, and Weak means 75th percentile or below."
            />

            <InfoBlock
              title="Insufficient Data"
              text="Some metrics need a minimum number of eligible users or rated bookings. If that minimum is not met, the dashboard may show Insufficient Data instead of a performance status."
            />
          </HelpSection>
        </div>
      </main>
    </div>
  );
}

function HelpSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-3">
      <h3 className="px-1 text-lg font-bold text-foreground">{title}</h3>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function MetricHelp({
  title,
  period,
  unit,
  description,
  formula,
  notes,
}: {
  title: string;
  period: string;
  unit: string;
  description: string;
  formula: string;
  notes?: string[];
}) {
  return (
    <div className="rounded-2xl border border-border/60 bg-card p-4 shadow-sm">
      <div>
        <h4 className="text-base font-semibold text-foreground">{title}</h4>

        <p className="mt-0.5 text-xs text-muted-foreground">
          {period} • {unit}
        </p>
      </div>

      <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
        {description}
      </p>

      <div className="mt-3 rounded-xl bg-primary/10 p-3">
        <p className="text-xs font-medium text-muted-foreground">Formula</p>
        <p className="mt-1 text-sm font-medium leading-relaxed text-foreground">
          {formula}
        </p>
      </div>

      {notes && notes.length > 0 && (
        <ul className="mt-3 list-disc space-y-1 pl-4 text-xs leading-relaxed text-muted-foreground">
          {notes.map((note) => (
            <li key={note}>{note}</li>
          ))}
        </ul>
      )}
    </div>
  );
}

function InfoBlock({
  title,
  text,
}: {
  title: string;
  text: string;
}) {
  return (
    <div className="rounded-2xl border border-border/60 bg-card p-4 shadow-sm">
      <h4 className="text-base font-semibold text-foreground">{title}</h4>
      <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
        {text}
      </p>
    </div>
  );
}
