/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaarthiRouteImport } from './routes/saarthi'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const SaarthiRoute = SaarthiRouteImport.update({
  id: '/saarthi',
  path: '/saarthi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/loading': typeof LoadingRoute
  '/saarthi': typeof SaarthiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/loading': typeof LoadingRoute
  '/saarthi': typeof SaarthiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/loading': typeof LoadingRoute
  '/saarthi': typeof SaarthiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/help' | '/impact' | '/loading' | '/saarthi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/help' | '/impact' | '/loading' | '/saarthi'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/help'
    | '/impact'
    | '/loading'
    | '/saarthi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  ImpactRoute: typeof ImpactRoute
  LoadingRoute: typeof LoadingRoute
  SaarthiRoute: typeof SaarthiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saarthi': {
      id: '/saarthi'
      path: '/saarthi'
      fullPath: '/saarthi'
      preLoaderRoute: typeof SaarthiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  ImpactRoute: ImpactRoute,
  LoadingRoute: LoadingRoute,
  SaarthiRoute: SaarthiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
